spring:
  application:
    name=Testes
  datasource:
    url: jdbc:h2:mem:testdb
    username: vktgabriel
    password: 1234
    driver-class-name: org.h2.Driver
  h2:
    console:
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true