variaveis:
  password:
    master: vktgabriel_rl_maeter_key

spring:
  application:
    name: rota-literaria

  datasource:
    username: vktgabriel
    password: upx-6-rota
    url: jdbc:postgresql://localhost:5432/rota-literaria
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: iniciativa.rotaliteraria@gmail.com
#    password: memw ivgh iame wgss
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#
#  data:
#    redis:
#      host: localhost
#      port: 6379