aws:
  s3:
    region: ${AWS_S3_REGION}
    accessKey: ${AWS_S3_ACCESS_KEY}
    secretKey: ${AWS_S3_SECRET_KEY}
    bucket-name: ${AWS_S3_BUCKET_NAME}

google:
  apiKey: ${GOOGLE_API_KEY}

spring:
  application:
    name: upx6
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  override-with-generic-response: false